apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: anupsharma329/node
    argocd-image-updater.argoproj.io/anupsharma329_node.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: directory
spec:
  project: default
  source:
    repoURL: https://github.com/anupsharma329/k8s-infra.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
