apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080   # Optional; K8s can auto-assign if you omit
